"""Generates rss.xml + sitemap.xml for the site from published articles."""
from xml.sax.saxutils import escape
from typing import List, Dict, Any

from blogboard.config.settings import app_settings


def _site_url() -> str:
    return app_settings.site_url.rstrip("/")


def generate_rss(articles: List[Dict[str, Any]]) -> str:
    site = _site_url()
    items = []
    for a in articles[:50]:
        link = f"{site}/post.html#id={escape(str(a.get('id', '')), {'\"': '&quot;'})}"
        items.append(
            "<item>\n"
            f"  <title>{escape(str(a.get('title', '')))}</title>\n"
            f"  <link>{link}</link>\n"
            f"  <guid>{link}</guid>\n"
            f"  <pubDate>{escape(str(a.get('date', '')))}</pubDate>\n"
            f"  <description>{escape(str(a.get('description', '')))}</description>\n"
            f"  <category>{escape(str(a.get('category', '')))}</category>\n"
            "</item>"
        )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n'
        "<channel>\n"
        "  <title>BlogBoard</title>\n"
        f"  <link>{site}</link>\n"
        "  <description>AI &amp; ML insights — autogenerated by BlogBoard</description>\n"
        f"  <atom:link href=\"{site}/rss.xml\" rel=\"self\" type=\"application/rss+xml\"/>\n"
        + "\n".join(items) + "\n"
        "</channel>\n"
        "</rss>"
    )


def generate_sitemap(articles: List[Dict[str, Any]]) -> str:
    site = _site_url()
    urls = [
        f"  <url><loc>{site}/index.html</loc></url>",
        f"  <url><loc>{site}/category.html</loc></url>",
        f"  <url><loc>{site}/search.html</loc></url>",
    ]
    for a in articles:
        loc = f"{site}/post.html#id={escape(str(a.get('id', '')), {'\"': '&quot;'})}"
        lastmod = escape(str(a.get("date", "")))
        urls.append(f"  <url><loc>{loc}</loc><lastmod>{lastmod}</lastmod></url>")
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(urls) + "\n"
        "</urlset>"
    )
