"""
build_site.py — BlogBoard site builder.

Self-heals registries (registers orphan .md files), then bakes the ENTIRE
site (article metadata + full markdown content) into js/site-data.js so the
frontend works with zero fetches: file://, offline, any static host.

Run standalone:  uv run python scripts/build_site.py
Called automatically by the validator after every publish.
"""

import json
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "blogboard" / "web"

CATEGORIES = ["ml", "dl", "statistics", "nlp", "cv", "genai", "ainews"]

LABELS = {
    "ml": "Machine Learning",
    "dl": "Deep Learning",
    "statistics": "Statistics for AI",
    "nlp": "Natural Language Processing",
    "cv": "Computer Vision",
    "genai": "Generative AI",
    "ainews": "AI News",
}

WORDS_PER_MINUTE = 200


def _read_time(text: str) -> str:
    return f"{max(1, -(-len(text.split()) // WORDS_PER_MINUTE))} min"


def _derive_meta(md_path: Path, cat: str) -> dict:
    """Derive registry metadata for an orphan article from its content."""
    text = md_path.read_text(encoding="utf-8")
    title = None
    first_para = None
    for line in text.splitlines():
        stripped = line.strip()
        if not title and stripped.startswith("# "):
            title = stripped[2:].strip()
        elif (
            not first_para
            and stripped
            and not stripped.startswith(("#", "```", "-", "*", "|", ">", "[!", "---"))
        ):
            first_para = stripped
        if title and first_para:
            break
    title = title or md_path.stem.replace("-", " ").title()
    first_para = first_para or f"An article about {title}."
    rel = md_path.relative_to(WEB).as_posix()
    mtime = datetime.fromtimestamp(md_path.stat().st_mtime, tz=UTC)
    return {
        "id": rel,
        "category": cat,
        "topic": title,
        "subtopics": "",
        "title": title,
        "description": first_para[:200],
        "date": mtime.strftime("%Y-%m-%d"),
        "tags": [cat],
        "readTime": _read_time(text),
        "file": rel,
        "coverImage": "",
    }


def self_heal_registries() -> list:
    """Register orphan .md files into their category registries. Returns healed IDs."""
    healed = []
    for cat in CATEGORIES:
        cat_dir = WEB / "blogs" / cat
        cat_dir.mkdir(parents=True, exist_ok=True)
        reg_path = cat_dir / "articles.json"

        # Load (or create) a valid registry
        articles = []
        if reg_path.exists():
            try:
                loaded = json.loads(reg_path.read_text(encoding="utf-8"))
                if isinstance(loaded, list):
                    articles = loaded
            except (json.JSONDecodeError, UnicodeDecodeError):
                print(f"  [HEAL] {cat}: corrupt registry — rebuilding")
        else:
            print(f"  [HEAL] {cat}: missing registry — creating")

        registered = {a.get("file") for a in articles}

        # Purge dead entries (file no longer exists)
        alive = []
        for a in articles:
            f = a.get("file", "")
            if (WEB / f).is_file():
                alive.append(a)
            else:
                print(f"  [HEAL] {cat}: removing dead entry {f}")
        articles = alive

        # Register orphans
        for md in sorted(cat_dir.glob("*.md")):
            rel = md.relative_to(WEB).as_posix()
            if rel not in registered:
                print(f"  [HEAL] {cat}: registering orphan {md.name}")
                articles.append(_derive_meta(md, cat))
                healed.append(rel)

        articles.sort(key=lambda x: x.get("date", ""), reverse=True)
        reg_path.write_text(json.dumps(articles, indent=2, ensure_ascii=False), encoding="utf-8")
    return healed


def build_site_data() -> Path:
    """Bake all registries + article contents into js/site-data.js."""
    categories = {}
    contents = {}

    for cat in CATEGORIES:
        reg_path = WEB / "blogs" / cat / "articles.json"
        try:
            articles = json.loads(reg_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            articles = []
        categories[cat] = articles
        for a in articles:
            md_path = WEB / a.get("file", "")
            if md_path.is_file():
                try:
                    contents[a["id"]] = md_path.read_text(encoding="utf-8")
                except OSError:
                    pass

    payload = {
        "generated": datetime.now(UTC).isoformat(timespec="seconds"),
        "categories": categories,
    }

    # Write as a JS file: metadata + a separate CONTENT map (markdown sources)
    def js_str(obj) -> str:
        return json.dumps(obj, ensure_ascii=False, indent=1)

    js = (
        "// AUTO-GENERATED by scripts/build_site.py — do not edit by hand.\n"
        "// Contains every article's metadata and full content. Regenerated on each publish.\n"
        f"window.SITE_DATA = {js_str(payload)};\n"
        f"window.SITE_CONTENT = {js_str(contents)};\n"
    )

    out = WEB / "js" / "site-data.js"
    out.write_text(js, encoding="utf-8")
    total = sum(len(v) for v in categories.values())
    print(
        f"  [BUILD] site-data.js: {total} articles, {len(contents)} contents "
        f"({out.stat().st_size // 1024} KB)"
    )
    return out


def build_all() -> Path:
    print("  [BUILD] Self-healing registries...")
    self_heal_registries()
    print("  [BUILD] Baking site data...")
    return build_site_data()


if __name__ == "__main__":
    out = build_all()
    print(f"Done → {out}")
